import streamlit as st
import src.st_utils as st_utils
import time
import pprint
import logging
from logging.config import fileConfig
import configparser
#from dotenv import load_dotenv


# BEGIN-1: Okta OIDC Addition:
import os

#load_dotenv()


logger = logging.getLogger()
# Initialize Streamlit app settings

st.set_page_config(page_title="Test Data Management", layout="wide", page_icon="📊")
st.title("Test Data Management")


config = configparser.ConfigParser()



st.write("")
Input = """
Test data management using synthetic data generated by AI offers a significant advantage over traditional methods. By leveraging AI algorithms, synthetic data can be created that closely resembles real-world data while maintaining privacy and confidentiality. This approach eliminates the need for sensitive or proprietary data, ensuring compliance with data protection regulations. Additionally, synthetic data can be generated on demand, reducing the time and cost associated with data acquisition and preparation. AI-generated synthetic data can also be customized to specific testing scenarios, enabling more targeted and effective testing.
 
"""
def stream_data():
    for word in Input.split(" "):
        yield word + " "
        time.sleep(0.01)
st.write_stream(stream_data)